---
repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.9.1
    values:
    - "./values.yaml"
    set:
      - name: installCRDs
        value: true
