name: Update version
on:
  push:
    branches:
      - 'renovate/*'
    paths:
      - '**/helmfile.yaml'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
    - name: Setup helmfile
      uses: mamezou-tech/setup-helmfile@v1.3.0
      with:
        helmfile-version: "v0.145.4"
    - name: Generate file
      uses: actions/checkout@v3
    - run: |
        helmfile template --file cert-manager/helmfile.yaml > cert-manager/cert-manager.yaml
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "[bot]: auto generate manifest for new version"
        git push

